[package]
name = "criner"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
description = "a platform for resumable mining of crates.io for knowledge and information"
publish = false
include = ["src/**/*", "Cargo.*"]
license = "MIT"
repository = "https://github.com/Byron/crates-io-cli-rs"
readme = "README.md"

[lib]
doctest = false

[dependencies]
quick-error = "1.2.3"
futures = { version = "0.3.4", features = ["thread-pool"]}
futures-timer = "3.0.1"
sled = { version = "0.31.0", features = ["compression"] }
crates-index-diff = "5.0.4"
prodash = { version = "1.0", path = "../prodash" }
rmp-serde = "0.14.0"
serde_derive = "1.0.104"
serde = "1.0.104"
humantime = "2.0.0"
log = "0.4.8"
async-std = { version = "1.5.0", default-features = false, features = ["unstable"] }
itertools = "0.8.2"
