[package]
name = "criner"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

[lib]
doctest = false

[features]
default = ["with-executor"]
with-executor = ["async-std"]

[dependencies]
quick-error = "1.2.3"
crates-index-diff = "5.0.1"
sled = "0.31.0"
async-std = { version = "1.4.0", optional = true }
rmp-serde = "0.14.0"
humantime = "2.0.0"
log = "0.4.8"
