os:
- linux
language: rust
rust:
- stable
- beta
- nightly
before_script:
- curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | sudo tar -xzC $PWD
- export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin/:$PATH
script:
- make tests

